### ISSUE TITLE
Comparison with SwiftCheck?

### ISSUE THREAD

**Issue by MaxDesiatov** [karwa/swift-checkit#1]
Thanks for the great library! Wholeheartedly agree with this one:

>Swift's protocols aren't just bags of syntax; there is some expected behaviour attached to each of them. Sometimes those expectations can be reflected in the type-system, but sometimes they have to be explained in documentation and left to the programmer. That's fine - but as software becomes more complex, it's easy to make changes which accidentally violate some subtle semantics of the protocol. That's why we write tests.

I had similar problems in a few projects, so I was using [`SwiftCheck`](https://github.com/typelift/SwiftCheck/) to get more coverage for some invariants that had to be maintained in my code. I was wondering how does Checkit compare to SwiftCheck?

**Comment by karwa** [comment]
Hey apologies for the delay 😄 

As far as I can tell, SwiftCheck does random instance generation and helps you test your type's own semantics. This is supposed to be an exercise routine for standard library protocols - checking that your custom `Collection` behaves like a `Collection` should. It doesn't say anything about your type's own semantics being correct (e.g. it doesn't test that a custom lazy-filter wrapper actually filters anything, but it checks that indexing operations work correctly for instances which purport to be empty or non-empty).

**Comment by MaxDesiatov** [comment]
Thanks for the clarification!
